# Generated by Django 4.2.2 on 2023-06-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'email': 'Email xxists already'}, max_length=250, unique=True, verbose_name='Email address'),
        ),
    ]
